### ISSUE TITLE
OpenStreetMap as a source of airport structural data

### ISSUE THREAD

**Issue by espinielli** [atmdata/atmdata#3]
It could be useful to be able to extract data from OSM via the [Overpass API](https://wiki.openstreetmap.org/wiki/Overpass_API)

Things like gates/stands, runway (thresholds' coordinates, width, length), for example
https://www.openstreetmap.org/#map=19/51.47123/-0.46122&layers=TD

**Comment by xoolive** [comment]
Indeed, I developed https://github.com/xoolive/cartotools in order to programmatically access data from OSM, including airport information.

Level of details is not very consistent. But for some airports (unrelated to the fact they are major or minor ones), we can get labelled parking positions and labelled taxiways.

**Comment by xoolive** [comment]
included in the website
